name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '10'
  PYTHON_VERSION: '3.12'

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Install dependencies
      run: uv sync --group test
      
    - name: Run linting
      run: uv run ruff check .
      
    - name: Run unit tests
      run: uv run pytest tests/unit -v --cov=src --cov-report=xml --cov-report=term-missing
      
    - name: Run integration tests
      run: uv run pytest tests/integration -v --cov=src --cov-append --cov-report=xml --cov-report=term-missing
      
    - name: Upload backend coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}
        
    - name: Configure npm for native dependencies
      run: |
        # Clear any existing cache that might have wrong binaries
        pnpm store prune
        # Set npm to rebuild native dependencies for current platform
        echo "target_platform=linux" >> ~/.npmrc
        echo "target_arch=x64" >> ~/.npmrc
        echo "cache_binary_host_mirror=https://github.com/oxc-project/binaries/releases/download" >> ~/.npmrc
        
    - name: Install dependencies with rebuild
      run: |
        # Install with platform-specific flags and rebuild native modules
        pnpm install --frozen-lockfile --force
        # Try to rebuild native dependencies if needed
        if [ -d "node_modules" ]; then
          pnpm rebuild || echo "Some native modules failed to rebuild, continuing..."
        fi
      
    - name: Verify installation
      run: |
        # Check if critical packages are properly installed
        node -e "console.log('Node.js version:', process.version, 'Platform:', process.platform, 'Arch:', process.arch)"
        # Test crypto.hash availability (requires Node.js 19+)
        node -e "try { require('crypto').hash('sha256', 'test'); console.log('Crypto.hash OK'); } catch(e) { console.log('Crypto.hash issue:', e.message); }"
        # Attempt to require problematic packages to verify they work
        node -e "try { require('@nuxt/eslint'); console.log('ESLint module OK'); } catch(e) { console.log('ESLint module issue:', e.message); }"
        
    - name: Run linting
      run: pnpm lint
      continue-on-error: true  # Don't fail the entire job if linting has issues
      
    - name: Run unit tests
      run: pnpm test:coverage
      
    - name: Upload frontend coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./frontend/coverage/coverage-final.json
        flags: frontend
        name: frontend-coverage
        fail_ci_if_error: false  # Don't fail if coverage upload fails

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail the entire workflow if security scan fails
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && github.actor != 'nektos/act' # Skip when running locally with act
      continue-on-error: true
      with:
        sarif_file: 'trivy-results.sarif'

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, security-scan]
    if: always()
    
    steps:
    - name: Check test results
      run: |
        echo "=== Quality Gate Results ==="
        
        # Critical tests that must pass
        CRITICAL_FAILED=false
        
        if [[ "${{ needs.backend-tests.result }}" != "success" ]]; then
          echo "❌ Backend tests failed - CRITICAL"
          CRITICAL_FAILED=true
        else
          echo "✅ Backend tests passed"
        fi
        
        if [[ "${{ needs.frontend-tests.result }}" != "success" ]]; then
          echo "❌ Frontend tests failed - CRITICAL" 
          CRITICAL_FAILED=true
        else
          echo "✅ Frontend tests passed"
        fi
        
        # Optional tests that provide information but don't block
        if [[ "${{ needs.e2e-tests.result }}" == "success" ]]; then
          echo "✅ E2E tests passed"
        elif [[ "${{ needs.e2e-tests.result }}" == "skipped" ]]; then
          echo "⏭️  E2E tests skipped (dependency failure)"
        else
          echo "⚠️  E2E tests failed - non-blocking"
        fi
        
        if [[ "${{ needs.security-scan.result }}" == "success" ]]; then
          echo "✅ Security scan passed"
        else
          echo "⚠️  Security scan failed - non-blocking"
        fi
        
        # Final decision
        if [[ "$CRITICAL_FAILED" == "true" ]]; then
          echo ""
          echo "❌ Quality gate FAILED - Critical tests must pass"
          exit 1
        else
          echo ""
          echo "✅ Quality gate PASSED - All critical tests successful! 🎉"
        fi
